[theme]
base = "dark"
primaryColor = "#2563eb"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#e2e8f0"

[server]
headless = true
port = 9000
enableCORS = false
enableXsrfProtection = true
